@startuml

title __SRC's Class Diagram__\n

  package  {
    class Account {
        - balanceCasino : int
        ~ userBalance : int
        ~ betPlace : int
        - multipler : int
        - isWinning : boolean
        + text : String
        + getCasinoBalance()
        + setCasinoBalance()
        + endGame()
        + getPayOut()
        - setBet()
        + validBet()
        + setMultipler()
        + getMultipler()
        + getUserBalance()
        + setWinning()
        + endOfHand()
        + userBalance()
        + casinoBalance()
    }
  }
  

  package  {
    class BlackJack {
    }
  }
  

  package  {
    class CardImages {
        {static} - img : BufferedImage
        + drawCard()
        {static} ~ main()
    }
  }
  

  package  {
    enum CardRanks {
      ACE
      TWO
      THREE
      FOUR
      FIVE
      SIX
      SEVEN
      EIGHT
      NINE
      TEN
      JACK
      QUEEN
      KING
      Default
      worth
    }
  }
  

  package  {
    enum CardSuits {
      Hearts
      Spades
      Diamonds
      Clubs
      Default
      color
    }
  }
  

  package  {
    class Cards {
        - array : boolean[][]
        - random : Random
        - CardRank : CardRanks[]
        - cardSuit : CardSuits[]
        - i : int
        + text : String
        + toCardName()
        + cardDealtRank()
        + cardDealtSuit()
        + resetChecker()
        + cardIllegalChecker()
    }
  }
  

  package  {
    class Casino {
        {static} ~ ac : Account
        {static} ~ card : Cards
        {static} ~ playerRank : CardRanks
        {static} ~ computerRank : CardRanks
        {static} ~ playerSuit : CardSuits
        {static} ~ computerSuit : CardSuits
        {static} ~ i : int
        {static} + main()
    }
  }
  

  package  {
    class HighLow {
        {static} + text : String
        {static} + userGuess : String
        {static} - i : int
        {static} - x : CardRanks
        {static} - xc : CardRanks
        {static} - y : CardSuits
        {static} - yc : CardSuits
        {static} - card : Cards
        {static} + startHighLower()
        {static} + HighLow()
        {static} - resetGame()
    }
  }
  

  package  {
    class War {
        {static} + text : String
        {static} + war()
    }
  }
  

  package  {
    class Window {
        - primaryStage : Stage
        {static} + main()
        + start()
        - menuBar()
        - WarWindow()
        - mainWindow()
        - highLowScene()
    }
  }
  

  package  {
    abstract class Parameters {
        + Parameters()
        {abstract} + getRaw()
        {abstract} + getUnnamed()
        {abstract} + getNamed()
    }
  }
  

  Window -up-|> Application
  Window +-down- Parameters


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
